### ISSUE TITLE
Try alternative paste services when one fails

### ISSUE THREAD

**Issue by Lonami** [Lonami/TelethonianBotExt#22]
del.dog dies often, but so do plenty other services. https://github.com/Lonami/TelethonianBotExt/blob/master/haste.py should fallback to different services (like hastebin, nekobin…) when the previous one fails.

**Comment by nitanmarcel** [comment]
Or paste.telethon.dev? del.dog is open source and under the MIT license so hosting it on a telethon subdomain wouldn't be so hard.

**Comment by nitanmarcel** [comment]
https://github.com/dogbin/dogbin

**Comment by kittyandrew** [comment]
> ...so hosting it on a telethon subdomain wouldn't be so hard.
haha, you are so wrong

**Comment by Lonami** [comment]
There are far simpler paste services and writing a custom one would be trivial. It's just a `POST` and making a new file with a random name.
